trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: finapi_rlinton_deploy
      trigger:
        branches:
          include:
            - main

variables:
  - group: LogAnalyticsSecrets

pool:
  name: student-lab-pool

steps:
  - script: |
      export LOG_ANALYTICS_WORKSPACE_ID=$(LOG_ANALYTICS_WORKSPACE_ID)
      export LOG_ANALYTICS_SHARED_KEY=$(LOG_ANALYTICS_SHARED_KEY)
      /azagent/venv/bin/python3 -m pytest -v --tb=line  -W "ignore::DeprecationWarning" -s tests/smoke_tests_centralized.py --junitxml=smoke-results.xml
    displayName: "Install dependencies"

  - script: |
      /azagent/venv/bin/python3 -m pytest -v --tb=line  -W "ignore::DeprecationWarning" -s tests/smoke_tests.py --junitxml=smoke-results.xml
    displayName: "Run full smoke test suite"


  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: 'smoke-results.xml'
      testRunTitle: 'Post-deployment Smoke Test'
      failTaskOnFailedTests: false
